# This workflow is based on pytest-blender which allows pytest to be used from inside Blender's python while running Blender in headless mode 
# https://github.com/mondeja/pytest-blender   qqq

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - macos-latest
        blender-version:
          - '3.3.12'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python v3.9
        id: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Cache Blender ${{ matrix.blender-version }}
        uses: actions/cache@v3
        id: cache-blender
        with:
          path: |
            blender-*
            _blender-executable-path.txt
          key: ${{ runner.os }}-${{ matrix.blender-version }}

      - name: Download Blender ${{ matrix.blender-version }}
        if: steps.cache-blender.outputs.cache-hit != 'true'
        id: download-blender
        run: |
          python -m pip install --upgrade blender-downloader
          printf "%s" "$(blender-downloader \
          ${{ matrix.blender-version }} --extract --remove-compressed \
          --quiet --print-blender-executable)" > _blender-executable-path.txt
          blender_executable="$(< _blender-executable-path.txt)"
          echo "{blender-executable}={blender_executable}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        id: install-dependencies
        run: |
          python -m pip install pytest-blender

          pip install flake8

          python -m pip install .[test]
          blender_executable="$(< _blender-executable-path.txt)"
          python_blender_executable="$(pytest-blender --blender-executable $blender_executable)"
          $python_blender_executable -m ensurepip
          $python_blender_executable -m pip install pytest

      - name: flake8 Lint
        run: flake8 . --exclude blender*,addon/,simulations/,blend/,test.py,tests/ --max-line-length 88

      - name: Print Blender Executable Path
        run: |
          echo "Blender Executable: ${{ steps.download-blender.outputs.blender-executable }}"
      
      - name: Test with pytest in Blender
        run: |
          pytest -svv --blender-executable "${{ steps.download-blender.outputs.blender-executable }}" tests/
      