# This workflow is based on pytest-blender which allows pytest to be used from inside Blender's python while running Blender in headless mode 
# https://github.com/mondeja/pytest-blender   qqq

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - ubuntu-latest
        blender-version:
          - '3.3'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python v3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Upgrade PIP
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        id: install-dependencies
        run: |
          python -m pip install .[test]
          python -m pip install pytest-blender
          pip install pylint
          pip install flake8
      - name: Check directory
        run: ls simulations
      - name: flake8 Lint with py-actions
        uses: py-actions/flake8@v2
        with:
          exclude: "simulations/"